ARCUS_APPLICATION_SAMPLE_IMAGE=jam2in/arcus-application-sample:0.0.1

build:
	@ docker build -t ${ARCUS_APPLICATION_SAMPLE_IMAGE} . --network=host

push:
	@ docker push ${ARCUS_APPLICATION_SAMPLE_IMAGE}
